/*

DML(Data Manipulation Language) : 데이터 조작어
 - SELECT, INSERT, UPDATE, DELETE

INSERT
INSERT INTO 테이블명(컬럼명1,컬럼명2...) VALUES(값1,값2...)
 - 테이블전체 데이터 컬럼 삽입 : 컬럼생략가능. 단, 컬럼 순서대로 넣어야한다
 - 일부 컬럼만 데이터 삽입

UPDATE 
UPDATE SET 테이블명=? [WHERE]
-- UPDATE 테이블명 SET 수정할컬럼명='바꿀내용' 

DELETE
DELETE FROM 테이블명 [WHERE]



*/


DELETE FROM MEMBER WHERE USER_NAME = 'USER01NAME';
UPDATE MEMBER SET USER_ID = 'USER00' WHERE USER_ID = 'USER000';
INSERT INTO MEMBER(USER_ID,USER_PWD,USER_NAME) VALUES('USER00','USER_PW00','USER01NAME','010-0000-0000');
DELETE FROM MEMBER WHERE USER_ID = 'USER03';
UPDATE MEMBER SET USER_ID = 'USER02' WHERE USER_ID = 'USER_01';
INSERT INTO MEMBER VALUES('USER02','USER_PW','USER01NAME','010-0000-0000');

INSERT INTO MEMBER VALUES('USER01','USER_PW','USER01NAME','010-0000-0000');
INSERT INTO MEMBER(USER_ID,USER_PWD,USER_NAME) VALUES('USER02','USER02_PW','USER0303');

-- UPDATE 테이블명 SET 수정할컬럼명='바꿀내용' 
UPDATE MEMBER SET USER_NAME = 'NOONE' WHERE USER_ID = 'USER01';

-- DELETE FROM 테이블명 [WHERE]
DELETE FROM MEMBER WHERE USER_ID = 'USER01';
DELETE FORM BOARD;
DELETE FROM BOARD WHERE BOARD_ID = '1';