/*
DDL(DATA DEFINITION LANGUAGE):  데이터 정의어
- CREATE, ALTER, RENAME, DROP, TRUNCATE 

DCL(Data Control Language) : 데이터 제어어
 - GRANT, REVOKE

TCL(Transaction Control Language) : 트랜잭션 제어어
 - COMMIT, ROLLBACK, SAVEPOINT



*/



/*

 ALTER : 객체 수정
 컬럼 추가/삭제, 제약조건 추가/삭제, 컬럼 자료형 변경, 디폴트값 변경 & 테이블명/컬럼명/제약조건명 변경

1)ALTER 컬럼 추가, 수정,삭제
ALTER TABLE 테이블명 ADD 추가할컬럼명 데이터타입
ALTER TABLE 테이블명 MODIFY 수정할컬럼명 데이터타입          ※ 수정할려는 크기가 더 작으면 에러
ALTER TABLE 테이블명 DROP COLUMN 삭제할 컬럼명;

2)ALTER 제약조건 추가, 삭제
ALTER TABLE 테이블명 ADD CONSTRAINT 제약조건명 제약조건(컬럼명);
ALTER TABLE 테이블명 MODIFY 컬럼명 CONSTRAINT 제약조건명;
※ NOT NULL은 이미 NULL이 기본으로 있는 상태이기 때문에 ADD가 아닌 MODIFY로 수정해야함
ALTER TABLE 테이블명 DROP CONSTRAINT 제약조건명;
MODIFY 컬럼명 NULL;

-- 한번에 여러개 삭제, 추가
ALTER TABLE 해당 테이블명
DROP CONSTRAINT 제약조건명
DROP CONSTRAINT 제약조건명
MODIFY 컬럼명 제약조건종류; 

*/



-- scott 사용자 생성 (비밀번호: tiger)
CREATE USER scott IDENTIFIED BY tiger;

-- scott 사용자의 기본 테이블스페이스를 USERS로 설정
ALTER USER scott DEFAULT TABLESPACE USERS;

-- scott 사용자에게 USERS 테이블스페이스에 무제한 용량 할당
ALTER USER scott QUOTA UNLIMITED ON USERS;

-- scott 사용자에게 RESOURCE 및 CONNECT 권한 부여
GRANT RESOURCE, CONNECT TO scott;







ALTER TABLE CHANGE_TABLE ADD PLUS_COLUMN VARCHAR2(10);
ALTER TABLE 테이블명 MODIFY 수정컬럼 NUMBER;
ALTER TABLE 드랍하기 DROP COLUMN PLUS_COLMN;


-- 컬럼레벨 & 테이블 레벨
-- 1)컬럼 레벨
CREATE TABLE COLUMN_LEVEL(
	USER_NO NUMBER PRIMARY KEY,
	USER_ID VARCHAR2(20) UNIQUE,
	USER_PWD VARCHAR2(20) NOT NULL,
	USER_NAME VARCHAR2(30) NOT NULL,
	GENDER VARCHAR2(1)
	EMAIL VARCHAR(30)
);

-- 2)테이블 레벨
CREATE TABLE TABLE_LEVEL(
	USER_NO,
	USER_ID VARCHAR2(20),
	USER_PWD VARCHAR2(20) NOT NULL,
	USER_NAME VARCHAR2(50) NOT NULL,
	GENDER VHARCHAR2(1)
	CONSTRAINT UNIQUE(USER_NO),
	CONSTRAINT PRIMARY KEY(USER_ID),
	CONSTRAINT FOREIGN KEY(USER_NAME) REFERENCES PARENT(USER_NAME),
	CONSTRAINT 제약조건명 CHECK(GENDER IN('M','F')
);



DESC USER_CONSTRAINTS;
SELECT * FROM USER_CONSTRAINTS;
DESC USER_CONSTRAINTS;
SELECT * FROM USER_CONSTRATINS;




ALTER TABLE 성적 ADD 등급 VARCHAR2(1);
ALTER TABLE 성적 MODIFY 등급 VARCHAR2(2);
ALTER TABLE 성적 DROP COLUMN 등급;

ALTER TABLE 성적 ADD 등급 VARCHAR2(1);
ALTER TABLE 성적 ADD CONSTRAINT CONSNAME CHECK(등급 IN('A','B'));
SELECT * FROM USER_CONSTRAINTS;
ALTER TABLE 성적 MODIFY 등급 CONSTRAINT CONSNAME NOT NULL;
ALTER TABLE 성적 MODIFY 등급 CONSTRAINT CONSNAME1 UNIQUE;
ALTER TABLE 성적 ADD 테스트 VARCHAR2(1);
ALTER TABLE 성적 MODIFY 테스트 NUMBER;
ALTER TABLE 성적 DROP COLUMN 테스트 CASCADE CONSTRAINTS;
ALTER TABLE 성적 ADD CONSTRAINT TESTCONS UNIQUE(테스트);
ALTER TABLE 성적 MODIFY 테스트 CONSTRAINT TESTCONS2 CHECK(테스트 IN('A','B'));

ALTER TABLE 성적 DROP CONSTRAINT CONSNAME;
ALTER TABLE 성적 DROP CONSTRAINT CONSNAME1;
ALTER TABLE 성적 MODIFY 성적(테스트) NULL;
--MODIFY 컬럼명 NULL;
ALTER TABLE 성적
DROP CONSTRAINT TESTCONS
DROP CONSTRAINT TESTCONS2
MODIFY 테스트 UNIQUE;

ALTER TABLE 사무용품 ADD 컴퓨터 VARCHAR2(10);
ALTER TABLE 사무용품 MODIFY 컴퓨터 DATE;
ALTER TABLE 사무용품 MODIFY 컴퓨터 VARCHAR2(20);
ALTER TABLE 사무용품 DROP COLUMN 컴퓨터 CASCADE CONSTRAINTS;

ALTER TABLE 사무용품 ADD CONSTRAINT OFC_OWN_UQ UNIQUE(컴퓨터);
ALTER TABLE 사무용품 MODIFY 컴퓨터 CONSTRAINT OFC_OWN_NN NOT NULL;



CREATE TABLE 테이블명(
    시퀀스넘버 NUMBER NOT NULL,
    식별번호 NUMBER NOT NULL,
    내용 VARCHAR(20),
    CONSTRAINT 테이블A_PK PRIMARY KEY(시퀀스넘버),
    CONSTRAINT 테이블A_KF FOREIGN KEY(식별번호) REFERENCES 테이블B(식별번호) ON DELETE RESTRICT
                                                                    또는 ON UPDATE SET NULL
);

-- 제약조건 이름짓기
-- 제약조건 이름짓기 네이밍룰 : 테이블명_컬럼명_제약조건타입
CREAT TABLE CONS_NAME(
    DATE1 VARCHAR2(50) CONSTRAINT CN_DT1_NN NOT NULL, -- 테이블명_컬럼명_제약조건타입
    DATE2 VARCHAR2(50) CONSTRAINT CN_DT2_PK PRIMARY KEY,
    DATE3 VARCHAR2(50) CONSTRAINT CN_DT3_UQ UNIQUE,
    DATE4 VARCHAR2(50) CONSTRAINT CN_DT4_CK CHECK(GENDER IN('M','W')),
    DATE5 VARCHAR2(50),
    DATE6 VARCHAR2(50),
    ANSWER VARCHAR2(1)
);
---- 제약조건 이름 테이블 생성 후 추가(ALTER)
ALTER TABLE CONS_NAME ADD FOREIGN KEY(DATE5)REFERENCES CON_NAME_ADD(DATE_ORIGIN);
ALTER TABLE CONS_NAME ADD CHECK(ANSWER IN('Y','N');
ALTER TABLE CONS_NAME ADD PRIMARY KEY(DATA6);

-- NOT NULL은 MODIFY 명령어로 변경

-- 사용자가 작성한 제약조건 확인 뷰
DESC USER_CONSTRAINTS; 
SELECT * FROM USER_CONSTRAINTS;

-- 컬럼레벨 & 테이블 레벨
-- 1)컬럼 레벨
CREATE TABLE T_MEMBER(
    USER_NO NUMBER UNIQUE,
    USER_ID VARCHAR2(20) PRIMARY KEY,
    USER_PWD VARCHAR2(20) NOT NULL,
    USER_NAME VARCHAR2(50) NOT NULL,
    GENDER VARCHAR2(1) NOT NULL,
    EMAIL VARCHAR2(30)     
);

-- 2)테이블 레벨
CREATE TABLE T_MEMBER(
    USER_NO NUMBER,
    USER_ID VARCHAR2(20),
    USER_PWD VARCHAR2(20) NOT NULL,
    USER_NAME VARCHAR2(50) NOT NULL,
    GENDER VARCHAR2(1) NOT NULL,
    EMAIL VARCHAR2(30)     
    CONSTRAINT UNIQUE(USER_NO), 
    CONSTRAINT PRIMARY KEY(USER_ID),
    CONSTRAINT FOREIGN KEY(USER_NAME) REFERENCES T_MEMBER(USER_NAME)
    CONSTRAINT 제약조건명 CHECK(GENDER IN('M','F')
);

----- 반복 연습 파트 -----
DESC USER_CONSTRAINTS;
SELECT * FROM USER_CONSTRAINTS;








