/*
DDL(DATA DEFINITION LANGUAGE):  데이터 정의어
- CREATE, ALTER, RENAME, DROP, TRUNCATE 

DCL(Data Control Language) : 데이터 제어어
 - GRANT, REVOKE

TCL(Transaction Control Language) : 트랜잭션 제어어
 - COMMIT, ROLLBACK, SAVEPOINT



*/



CREATE TABLE 테이블명(
    시퀀스넘버 NUMBER NOT NULL,
    식별번호 NUMBER NOT NULL,
    내용 VARCHAR(20),
    CONSTRAINT 테이블A_PK PRIMARY KEY(시퀀스넘버),
    CONSTRAINT 테이블A_KF FOREIGN KEY(식별번호) REFERENCES 테이블B(식별번호) ON DELETE RESTRICT
                                                                    또는 ON UPDATE SET NULL
);

-- 제약조건 이름짓기
-- 제약조건 이름짓기 네이밍룰 : 테이블명_컬럼명_제약조건타입
CREAT TABLE CONS_NAME(
    DATE1 VARCHAR2(50) CONSTRAINT CN_DT1_NN NOT NULL, -- 테이블명_컬럼명_제약조건타입
    DATE2 VARCHAR2(50) CONSTRAINT CN_DT2_PK PRIMARY KEY,
    DATE3 VARCHAR2(50) CONSTRAINT CN_DT3_UQ UNIQUE,
    DATE4 VARCHAR2(50) CONSTRAINT CN_DT4_CK CHECK(GENDER IN('M','W')),
    DATE5 VARCHAR2(50),
    DATE6 VARCHAR2(50),
    ANSWER VARCHAR2(1)
);
---- 제약조건 이름 테이블 생성 후 추가(ALTER)
ALTER TABLE CONS_NAME ADD FOREIGN KEY(DATE5)REFERENCES CON_NAME_ADD(DATE_ORIGIN);
ALTER TABLE CONS_NAME ADD CHECK(ANSWER IN('Y','N');
ALTER TABLE CONS_NAME ADD PRIMARY KEY(DATA6);

-- NOT NULL은 MODIFY 명령어로 변경

-- 사용자가 작성한 제약조건 확인 뷰
DESC USER_CONSTRAINTS; 
SELECT * FROM USER_CONSTRAINTS;

-- 컬럼레벨 & 테이블 레벨
-- 1)컬럼 레벨
CREATE TABLE T_MEMBER(
    USER_NO NUMBER UNIQUE,
    USER_ID VARCHAR2(20) PRIMARY KEY,
    USER_PWD VARCHAR2(20) NOT NULL,
    USER_NAME VARCHAR2(50) NOT NULL,
    GENDER VARCHAR2(1) NOT NULL,
    EMAIL VARCHAR2(30)     
);

-- 2)테이블 레벨
CREATE TABLE T_MEMBER(
    USER_NO NUMBER,
    USER_ID VARCHAR2(20),
    USER_PWD VARCHAR2(20) NOT NULL,
    USER_NAME VARCHAR2(50) NOT NULL,
    GENDER VARCHAR2(1) NOT NULL,
    EMAIL VARCHAR2(30)     
    CONSTRAINT UNIQUE(USER_NO), 
    CONSTRAINT PRIMARY KEY(USER_ID),
    CONSTRAINT FOREIGN KEY(USER_NAME) REFERENCES T_MEMBER(USER_NAME)
    CONSTRAINT 제약조건명 CHECK(GENDER IN('M','F')
);

----- 반복 연습 파트 -----
DESC USER_CONSTRAINTS;
SELECT * FROM USER_CONSTRAINTS;








