/*
DDL(DATA DEFINITION LANGUAGE):  데이터 정의어
- CREATE, ALTER, RENAME, DROP, TRUNCATE 

DCL(Data Control Language) : 데이터 제어어
 - GRANT, REVOKE

TCL(Transaction Control Language) : 트랜잭션 제어어
 - COMMIT, ROLLBACK, SAVEPOINT



*/



/*

 ALTER : 객체 수정
 컬럼 추가/삭제, 제약조건 추가/삭제, 컬럼 자료형 변경, 디폴트값 변경 & 테이블명/컬럼명/제약조건명 변경

1)ALTER 컬럼 추가, 수정,삭제
ALTER TABLE 테이블명 ADD 추가할컬럼명 데이터타입
ALTER TABLE 테이블명 MODIFY 수정할컬럼명 데이터타입          ※ 수정할려는 크기가 더 작으면 에러
ALTER TABLE 테이블명 DROP COLUMN 삭제할 컬럼명;

2)ALTER 제약조건 추가, 수정,삭제
ALTER TABLE 테이블명 ADD CONSTRAINT 제약조건명 제약조건(컬럼명);
ALTER TABLE 테이블명 MODIFY 컬럼명 CONSTRAINT 제약조건명;
※ NOT NULL은 이미 NULL이 기본으로 있는 상태이기 때문에 ADD가 아닌 MODIFY로 수정해야함

*/
ALTER TABLE 사무용품 ADD 컴퓨터 VARCHAR2(10);
ALTER TABLE 사무용품 MODIFY 컴퓨터 DATE;
ALTER TABLE 사무용품 MODIFY 컴퓨터 VARCHAR2(20);
ALTER TABLE 사무용품 DROP COLUMN 컴퓨터 CASCADE CONSTRAINTS;


CREATE TABLE 테이블명(
    시퀀스넘버 NUMBER NOT NULL,
    식별번호 NUMBER NOT NULL,
    내용 VARCHAR(20),
    CONSTRAINT 테이블A_PK PRIMARY KEY(시퀀스넘버),
    CONSTRAINT 테이블A_KF FOREIGN KEY(식별번호) REFERENCES 테이블B(식별번호) ON DELETE RESTRICT
                                                                    또는 ON UPDATE SET NULL
);

-- 제약조건 이름짓기
-- 제약조건 이름짓기 네이밍룰 : 테이블명_컬럼명_제약조건타입
CREAT TABLE CONS_NAME(
    DATE1 VARCHAR2(50) CONSTRAINT CN_DT1_NN NOT NULL, -- 테이블명_컬럼명_제약조건타입
    DATE2 VARCHAR2(50) CONSTRAINT CN_DT2_PK PRIMARY KEY,
    DATE3 VARCHAR2(50) CONSTRAINT CN_DT3_UQ UNIQUE,
    DATE4 VARCHAR2(50) CONSTRAINT CN_DT4_CK CHECK(GENDER IN('M','W')),
    DATE5 VARCHAR2(50),
    DATE6 VARCHAR2(50),
    ANSWER VARCHAR2(1)
);
---- 제약조건 이름 테이블 생성 후 추가(ALTER)
ALTER TABLE CONS_NAME ADD FOREIGN KEY(DATE5)REFERENCES CON_NAME_ADD(DATE_ORIGIN);
ALTER TABLE CONS_NAME ADD CHECK(ANSWER IN('Y','N');
ALTER TABLE CONS_NAME ADD PRIMARY KEY(DATA6);

-- NOT NULL은 MODIFY 명령어로 변경

-- 사용자가 작성한 제약조건 확인 뷰
DESC USER_CONSTRAINTS; 
SELECT * FROM USER_CONSTRAINTS;

-- 컬럼레벨 & 테이블 레벨
-- 1)컬럼 레벨
CREATE TABLE T_MEMBER(
    USER_NO NUMBER UNIQUE,
    USER_ID VARCHAR2(20) PRIMARY KEY,
    USER_PWD VARCHAR2(20) NOT NULL,
    USER_NAME VARCHAR2(50) NOT NULL,
    GENDER VARCHAR2(1) NOT NULL,
    EMAIL VARCHAR2(30)     
);

-- 2)테이블 레벨
CREATE TABLE T_MEMBER(
    USER_NO NUMBER,
    USER_ID VARCHAR2(20),
    USER_PWD VARCHAR2(20) NOT NULL,
    USER_NAME VARCHAR2(50) NOT NULL,
    GENDER VARCHAR2(1) NOT NULL,
    EMAIL VARCHAR2(30)     
    CONSTRAINT UNIQUE(USER_NO), 
    CONSTRAINT PRIMARY KEY(USER_ID),
    CONSTRAINT FOREIGN KEY(USER_NAME) REFERENCES T_MEMBER(USER_NAME)
    CONSTRAINT 제약조건명 CHECK(GENDER IN('M','F')
);

----- 반복 연습 파트 -----
DESC USER_CONSTRAINTS;
SELECT * FROM USER_CONSTRAINTS;








