




spring:
  # db 연결정보 setting
  datasource:
    username: root
    passwor: 1234
    url: jdbc:mariadb://localhost:3307/profile
    driver-class-name: org.mariadb.jdbc.Driver
  
  # View Template : thymeleaf 설정 setting
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false

server:
  port: 9092

mybatis:
  mapper-locations:
  - classpath:config/mapper/**.xml
  configuration:
  # snake_case -> camelCase 적용
    map-underscore-to-camel-case: true


